version: '3.8'

services:
  db:
    image: mongo:latest
    volumes:
      - db_data:/data/db

  app:
    build:
      context: .  # Mengarah ke root proyek
      dockerfile: Dockerfile  # Tentukan Dockerfile jika namanya berbeda
    ports:
      - '4000:4000'  
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/testdb

volumes:
  db_data:
